#!/bin/bash
#
# LMeve GetMe Package Generator
# This script creates a personalized setup package for users
#
# Usage: ./generate-package.sh [config-file]
#

set -euo pipefail

# Default configuration - can be overridden by config file or environment variables
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-lmeve}"
MYSQL_ROOT_USER="${MYSQL_ROOT_USER:-root}"
MYSQL_ROOT_PASS="${MYSQL_ROOT_PASS:-}"
LMEVE_USER="${LMEVE_USER:-lmeve}"
LMEVE_PASS="${LMEVE_PASS:-}"
SDE_SOURCE="${SDE_SOURCE:-fuzzwork}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}LMeve GetMe Package Generator${NC}"
echo "======================================"

# Load config file if provided
if [ $# -gt 0 ] && [ -f "$1" ]; then
    echo -e "${YELLOW}Loading configuration from: $1${NC}"
    source "$1"
fi

# Validate required configuration
if [ -z "$MYSQL_ROOT_PASS" ] || [ -z "$LMEVE_PASS" ]; then
    echo "ERROR: Required configuration missing!"
    echo ""
    echo "Please set the following environment variables or create a config file:"
    echo "  MYSQL_ROOT_PASS - MySQL root password"
    echo "  LMEVE_PASS - Password for LMeve database user"
    echo ""
    echo "Optional variables:"
    echo "  DB_HOST - Database host (default: localhost)"
    echo "  DB_PORT - Database port (default: 3306)"
    echo "  MYSQL_ROOT_USER - MySQL root username (default: root)"
    echo "  LMEVE_USER - LMeve database username (default: lmeve)"
    echo "  SDE_SOURCE - SDE data source (default: fuzzwork)"
    echo ""
    echo "Example config file (config.env):"
    echo "  MYSQL_ROOT_PASS=\"your-root-password\""
    echo "  LMEVE_PASS=\"your-lmeve-password\""
    echo "  DB_HOST=\"192.168.1.100\""
    echo "  LMEVE_USER=\"myuser\""
    echo ""
    exit 1
fi

# Create package directory
PACKAGE_DIR="lmeve-getme-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$PACKAGE_DIR"

echo "Creating package in: $PACKAGE_DIR"

# Copy and customize the main script
sed -e "s/\${DB_HOST:-localhost}/$DB_HOST/g" \
    -e "s/\${DB_PORT:-3306}/$DB_PORT/g" \
    -e "s/\${DB_NAME:-lmeve}/$DB_NAME/g" \
    -e "s/\${MYSQL_ROOT_USER:-root}/$MYSQL_ROOT_USER/g" \
    -e "s/\${MYSQL_ROOT_PASS:-}/$MYSQL_ROOT_PASS/g" \
    -e "s/\${LMEVE_USER:-lmeve}/$LMEVE_USER/g" \
    -e "s/\${LMEVE_PASS:-}/$LMEVE_PASS/g" \
    -e "s/\${SDE_SOURCE:-fuzzwork}/$SDE_SOURCE/g" \
    getme-lmeve.sh > "$PACKAGE_DIR/getme-lmeve.sh"

chmod +x "$PACKAGE_DIR/getme-lmeve.sh"

# Copy schema file if it exists
if [ -f "lmeve-schema.sql" ]; then
    cp lmeve-schema.sql "$PACKAGE_DIR/"
    echo "✓ Included LMeve schema"
elif [ -f "../database/lmeve-schema.sql" ]; then
    cp ../database/lmeve-schema.sql "$PACKAGE_DIR/"
    echo "✓ Included LMeve schema"
else
    echo "⚠ Warning: lmeve-schema.sql not found - package will skip schema import"
fi

# Create README
cat > "$PACKAGE_DIR/README.txt" << EOF
LMeve GetMe Setup Package
========================

Generated: $(date)
Configuration:
  Database Host: $DB_HOST:$DB_PORT  
  MySQL Root User: $MYSQL_ROOT_USER
  LMeve User: $LMEVE_USER
  SDE Source: $SDE_SOURCE

QUICK START:
-----------
1. Upload this entire folder to your database server
2. Make the script executable: chmod +x getme-lmeve.sh
3. Run: sudo ./getme-lmeve.sh

That's it! The script will:
✓ Create databases (lmeve, EveStaticData)
✓ Create user: $LMEVE_USER  
✓ Import LMeve schema
✓ Download and import latest SDE data
✓ Verify everything works

REQUIREMENTS:
------------
- MySQL/MariaDB server running
- Root/admin access to MySQL
- Internet connection (for SDE download)
- Sufficient disk space (~500MB for SDE data)

TROUBLESHOOTING:
---------------
- Make sure MySQL is running and accessible
- Verify the root password is correct
- Check firewall settings if connecting to remote MySQL
- Ensure sufficient disk space for SDE data

MANUAL STEPS (if automated script fails):
----------------------------------------
1. Create databases:
   CREATE DATABASE lmeve;
   CREATE DATABASE EveStaticData;

2. Create user:
   CREATE USER '$LMEVE_USER'@'%' IDENTIFIED BY '[password]';
   GRANT ALL ON lmeve.* TO '$LMEVE_USER'@'%';
   GRANT ALL ON EveStaticData.* TO '$LMEVE_USER'@'%';

3. Import schema:
   mysql -u $LMEVE_USER -p lmeve < lmeve-schema.sql

4. Download and import SDE:
   wget https://www.fuzzwork.co.uk/dump/latest/eve.db.bz2
   bunzip2 eve.db.bz2
   mysql -u $LMEVE_USER -p EveStaticData < eve.db

SUPPORT:
-------
- Check the LMeve documentation
- Verify your MySQL configuration
- Test network connectivity to database server

Generated by LMeve Database Setup Tool
EOF

# Create verification script
cat > "$PACKAGE_DIR/verify-setup.sh" << 'EOF'
#!/bin/bash
#
# LMeve Setup Verification Script
# Run this to verify your database setup is working
#

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-3306}"
LMEVE_USER="${LMEVE_USER:-lmeve}"
LMEVE_PASS="${LMEVE_PASS:-}"

if [ -z "$LMEVE_PASS" ]; then
    echo "Enter LMeve database password:"
    read -s LMEVE_PASS
fi

echo "Verifying LMeve database setup..."
echo "=================================="

# Test lmeve database
echo -n "Testing lmeve database access... "
if mysql -u"$LMEVE_USER" -p"$LMEVE_PASS" -h"$DB_HOST" -P"$DB_PORT" -e "USE lmeve; SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='lmeve';" >/dev/null 2>&1; then
    LMEVE_TABLES=$(mysql -u"$LMEVE_USER" -p"$LMEVE_PASS" -h"$DB_HOST" -P"$DB_PORT" -sN -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='lmeve';")
    echo "✓ OK ($LMEVE_TABLES tables)"
else
    echo "✗ FAILED"
fi

# Test SDE database
echo -n "Testing EveStaticData database access... "
if mysql -u"$LMEVE_USER" -p"$LMEVE_PASS" -h"$DB_HOST" -P"$DB_PORT" -e "USE EveStaticData; SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='EveStaticData';" >/dev/null 2>&1; then
    SDE_TABLES=$(mysql -u"$LMEVE_USER" -p"$LMEVE_PASS" -h"$DB_HOST" -P"$DB_PORT" -sN -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='EveStaticData';")
    echo "✓ OK ($SDE_TABLES tables)"
else
    echo "✗ FAILED"
fi

# Test specific SDE tables
echo -n "Testing key SDE tables... "
if mysql -u"$LMEVE_USER" -p"$LMEVE_PASS" -h"$DB_HOST" -P"$DB_PORT" -e "SELECT COUNT(*) FROM EveStaticData.invTypes LIMIT 1;" >/dev/null 2>&1; then
    echo "✓ OK"
else
    echo "✗ FAILED"
fi

echo ""
echo "Database connection string for LMeve:"
echo "Host: $DB_HOST"
echo "Port: $DB_PORT"
echo "Username: $LMEVE_USER"
echo "Password: [hidden]"
echo "Database: lmeve"
EOF

chmod +x "$PACKAGE_DIR/verify-setup.sh"

# Create archive
echo "Creating package archive..."
tar -czf "$PACKAGE_DIR.tar.gz" "$PACKAGE_DIR"

echo ""
echo -e "${GREEN}✓ Package created successfully!${NC}"
echo ""
echo "Package contents:"
echo "  📦 $PACKAGE_DIR.tar.gz (compressed archive)"
echo "  📁 $PACKAGE_DIR/ (directory)"
echo "    ├── getme-lmeve.sh (main setup script)"
echo "    ├── lmeve-schema.sql (database schema)"
echo "    ├── verify-setup.sh (verification script)"
echo "    └── README.txt (instructions)"
echo ""
echo "To use:"
echo "  1. Transfer $PACKAGE_DIR.tar.gz to your database server"
echo "  2. Extract: tar -xzf $PACKAGE_DIR.tar.gz"
echo "  3. Run: cd $PACKAGE_DIR && sudo ./getme-lmeve.sh"
echo ""